services:
  mongodb:
    image: mongo:7
    container_name: cloudvault-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - cloudvault_mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: cloudvault_db

volumes:
  cloudvault_mongo_data:
